# Change these first
owner: lucach # Your GitHub username
repo: luce-status # Your GitHub repository name

# Add your sites here
sites:
  - name: ExpressionTutor
    url: https://expressiontutor.org
  - name: QuizPlatform
    url: https://quiz.lumi.inf.usi.ch
  - name: QuizPlatform (Test)
    url: https://test.quiz.lumi.inf.usi.ch
  - name: QuizPlatform (Demo)
    url: https://demo.quiz.lumi.inf.usi.ch
    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  publish: true
  baseUrl: /luce-status
  logoUrl: https://raw.githubusercontent.com/lucach/luce-status/master/luce.svg
  name: LuCE monitor
  introTitle: LuCE websites monitor
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
